import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header/Header'
import Image from 'next/image'

const Home: NextPage = () => {
    return (
        <div className="h-[200vh]">
            <Head>
                <title>Airbnb</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="md:mt-44 ">
                <div className="w-full aspect-auto relative h-[700px]  md:h-[600px] lg:h-[700px]">
                    <Image
                        src="/main.png"
                        alt="A man in a camping"
                        layout="fill"
                        objectFit="cover"
                        className="md:!object-contain"
                    />
                </div>
                <div className="text-white text-center space-y-3">
                    <h1 className="text-2xl font-bold">
                        Not sure where to go? Perfect
                    </h1>
                    <button className="text-lg bg-gray-100 text-purple-700 font-semibold px-4 py-2 rounded-full">
                        I&apos;m flexible
                    </button>
                </div>
            </section>
        </div>
    )
}

export default Home
